export const UPDATE_INGREDIENT_AMOUNT = "UPDATE_INGREDIENT_AMOUNT";
export const UPDATE_CHECKOUT_FORM = "UPDATE_CHECKOUT_FORM";
export const RESET_STATE = "RESET_STATE";

export const LOAD_ORDERS = "LOAD_ORDERS";

export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED";
